let listaProduct = [{
    id:1,
    name  : "Itachi Uchiha",
    price : 99.00,
    category : "Naruto",
    image : "./img/Naruto/itachi.png",
    alt:"Personagem itachi",
    description:"action figure Itachi uchiha em plastico",
},{
    id:2,
    name  : "Naruto e Sasuke",
    price : 107.00,
    category : "Naruto",
    image : "./img/Naruto/sasukeNaruto.png",
    description:"action figure Naruto e Sasuke em plastico",
    alt:"Naruto e sasuke correndo",
},{
    id:3,
    name  : "Kit 6 personagens",
    price : 235.00,
    category : "Naruto",
    image : "./img/Naruto/seisPersonagens.png",
    alt:"Kit de personagens de naruto",
    description:"action figure Naruto Uzumaki em plastico",
},{
    id:4,
    name  : "Barba Branca",
    price : 66.00,
    category : "One Piece",
    image : "./img/One Piece/Rectangle 33.png",
    alt:"Personagem Barba Branca",
    description:"action figure Barba branca em plastico",
},{
    id:5,
    name  : "Roronoa Zoro",
    price : 70.00,
    category : "One Piece",
    image : "./img/One Piece/Rectangle 7.png",
    alt:"Personagem Rorona Zoro",
    description:"action figure Roronoa Zoro em plastico",
},{
    id:6,
    name  : "Lady Figth",
    price : 49.00,
    category : "One Piece",
    image : "./img/One Piece/action-figure-one-piece-lady-fight 1.png",
    alt:"Personagem Lady Figth",
    description: "action figure Lady Figth em plastico",
},{
    id:7,
    name : "Vegetto",
    price : 25.00,
    category : "Dragon Ball",
    image :"./img/Dargon Ball/Rectangle 11.png",
    alt:"Personagem Vegetto",
    description: "action figure Vegetto em plastico",
},{
    id:8,
    name : "Bradock",
    price : 69.00,
    category : "Dragon Ball",
    image :"./img/Dargon Ball/Rectangle 6.png",
    alt:"Personagem Bradock",
    description: "action figure Bradock em plastico",
},{
    id:9,
    name : "Bulma",
    price : 98.00,
    category : "Dragon Ball",
    image :"./img/Dargon Ball/product-image-1403256562 1.png",
    alt:"Personagem Bulma",
    description: "action figure Bulma em plastico",
}]